# Generated by Django 5.2.1 on 2025-07-17 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('endereco_padrao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço Padrão')),
                ('cidade_padrao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade Padrão')),
                ('estado_padrao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Padrão')),
                ('cep_padrao', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP Padrão')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
